### ISSUE TITLE
Add to FAQ: How do I create the path in an *.amd.json file?

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/amber-documentation#44]
Answer
1. each library needs its own .amd.json file in the root directory of the project
2. the path is relative to the library directory. Every single mapping is always resolved from the directory of the library.
3. the *.amd.json files are used by `grunt devel` to construct a `config.js` file.

Some examples of *.amd.json files
http://stackoverflow.com/questions/27374889/how-to-add-a-non-amber-library-with-bower-for-example-processing-js

**Comment by ghost** [comment]
It's a bit more complex. Only those libraries that are not Amber-aware need their own file. And mapping  drops the final ",js", which creates confusion with mappings like `"jquery-ui": "jquery-ui"` which looks like it points to directory, but it in fact points to file named similarly inside that directory.

There should be examples - but how to show them without scaring people off?

**Comment by hhzl** [comment]
You do not scare people off if you have enough examples and explain them painstakingly correct with enough redundancy.

And you proceed from simple cases (which have enough context to be easily understandabe) to somewhat seemingly weird cases like 

```
        "jquery-ui"  :   "jquery-ui"
```

The problem here is that the configuration file does not bear much semantics and looks tautologic whereas in fact we deal with homographs (things which are written the same but refer to different things).  The meaning can be discovered by having a look at the context (directory/file layout structure in this case).

So we need to tell people what  the left hand  "jquery-ui" is and what is the right hand  "jquery-ui" is.

**Comment by ghost** [comment]
Are examples in README of https://github.com/herby/amd-config-builder bad? Or just not explained good enough?

Hannes Hirzel wrote:

**Comment by hhzl** [comment]
The examples of https://github.com/herby/amd-config-builder are fine but need some more comments I think.  

``` js
//<root>/jquery.amd.json
{
  "paths": {
    "jquery": "jquery.min"
  }
}
```

"jquery" refers to a module name whereas "jquery.min" refers to a file "jquery.min.js"

**Comment by ghost** [comment]
Well, it should not point to .min, as `amber deploy` does minify all at once. I should probably fix that README...

Hannes Hirzel wrote:

**Comment by hhzl** [comment]
Yes, but the .min question is another issue....#47

**Comment by sebastianconcept** [comment]
Yes the minification is offtopic here and I'm skeptic with @herby recommendation on not using min files.

@herby do you guarantee that Amber's minification process will end up being as good (equal or better) than the vendor's own minification?

If you can guarantee that, your recommendation can hold ground, if it doesn't then it would be flawed and, we could mention it as option but we shouldn't recommend it. 

So, there is that guarantee or not?

**Comment by ghost** [comment]
Sebastian Sastre wrote:

> Yes the minification is offtopic here and I'm skeptic with @herby 
> https://github.com/herby recommendation on not using them.
> 
> @herby https://github.com/herby do you guarantee that Amber's 
> minification process will end up being as good (equal or better) than 
> the vendors own minification?
> 
> If you can guarantee that, your recommendation can hold ground, if it 

This is silly. Of course there can be one case when one vendor does its one .min.js file better than requirejs's minifier does. You cannot want guarantees here, for 100% of cases.

If you mean generally, then yes, requirejs's minification is as good as others out there. You can even select which one you want between a few options, if you're picky about that.

> doesn't then it would be flawed and, we could mention it as option but 
> we shouldn't recommend it.

We should. People should not be taught bad habits. Using .min.js during development is one.

> So, there is that gua
> rantee or not?

No.
OTOH, there never be a guarantee. This is same requirement as if you wanted a GUARANTEE that you will always be treated fair during trial. Once world war starts and certain group of people will begin to spread the final worldwide caliphate, you will NOT be treated fair during a trial. Even if you think that civilised democracy in which you are now gives such guarantee. It does not.
Nor will you ever get a guarantee that requirejs will minify better than the vendor. You even do not have the guarantee that vendor uses the best minifier.

WTF, really.

Guarantee.

_facepalm_

Guarantee. In SW.

Am I in a Beckett's play?

**Comment by hhzl** [comment]
@sebastianconcept , @herby Please move this lively discussion to #47 .BTW I agree that we should not use minified files during development :-)

**Comment by sebastianconcept** [comment]
I agree that for development one, sometimes, needs or find convenient to use unminified code. Mostly of the time? not at all.

And yes, I am picky about the size of the project builds as any other good CTO, CEO, engineer or plain freelancer programer should be.

So, filtering out your emotional reaction, note that your analogy with a socioeconomic system @herby doesn't apply because Minification is pretty much a mathematical process that can have a measurable input-output ratio. Having that in mind, the guarantee I asked about is if it's mathematically true that we provide a  `Amber.min(source)<=Vendor.min(source)`.

If we cannot, then it's okay to say it and show people the option to make whatever they think is best _for themselves_.

**Comment by ghost** [comment]
@sebastianconcept What you are doing here is called "attacking the straw man", a logical fallacy which first points to a "flaw" created on object of attack by putting it on wrong context, then attacking it in that context and. surprisingly, winning. Since there are many minifiers out there, no one can guarantee you that minifier A is better on file B compared to minification used by the vendor (but also, no one can guarantee you that minification provided by vendor is best). And you know this is not possible; nevertheless, you keep asking for guarantee you know you cannot obtain. These fallacies are used to manipulate those who can not see them to falsely accuse object of attack of being flawed. Stop. Thanks.

Beyond fallacies, in real life it should be enough if `f(x) <= (1+tolerance) g(x)` to treat them comparable. If you take into account that you minify _everything_ and that you can select the method of minifying (in the last resort by eschewing requirejs minification and injecting your own minifier into / after requirejs:deploy task in Gruntfile), the likelihood that you get visibly worse result, overall, than picking vendor's pre-minified files, is really, I mean _really_ small. Complications of selecting `.min` / `.nomin` per library, bringing many combinations to the process, and even cursing a library that is so idiotic as to provide its local.amd.json with non-min mapping and you must then somehow shadow with .min is not worth a few percent of size.

BTW, as far as I can conclude, `.min.js` files were created for times when there were no builders and concatenators and people loaded libraries mostly via `<script>` tag, one for each library. In the scenario when we actually have the builder, it is (IMO) really silly to try to inject these preminified files there. I think age of `.min.js` is over and vendor should not produce them any more.

If someone wants to complicate his life to save a few percent, let him do it. But not by default (and I am convinced he would save more if he just used better minifier on the overall build, instead of trying to reuse preminified files).

**Comment by hhzl** [comment]
Coming back to the original question stated in the title of this issue. Here is a modified and hopefully better proposal for an answer. @herby and @sebastianconcept what do you think?

**Answer**
1. each library needs its own `local.amd.json` file in the root directory of the library.
2. the path used in `local.amd.json` is relative to the library directory. Every single mapping is always resolved from the directory of the library.
3. the *.amd.json files are used by `grunt devel` to construct a `config.js` file.
4. some libraries do not provide a `local.amd.json`. In that case you have to provide an `*.amd.json` file named `librarydirectoryname.amd.json` and keep it in the root directory of your project, the project which uses the library.

Some examples of *.amd.json files
- https://github.com/herby/amd-config-builder
- http://stackoverflow.com/questions/27374889/how-to-add-a-non-amber-library-with-bower-for-example-processing-js

**Comment by sebastianconcept** [comment]
Great answer @herby thanks!

I totally agree with this:

"If someone wants to complicate his life to save a few percent, let him do it. But not by default (and I am convinced he would save more if he just used better minifier on the overall build, instead of trying to reuse preminified files)."

In the reviewed version I've recently posted I think that all points got addressed.

@hhzl can you put that text in a google doc? it will make our life easier to review and comment on sentences.

Another thing.. I'd review the question itself into:

"I am integrating a JavaScript library and I need to add it's *.amd.json file, what should I use as path there?"

because it provides full sense of what's about (more readable out of contex, better SEO, etc)

**Comment by hhzl** [comment]
@sebastianconcept I have added the question and answer [here](https://github.com/amber-smalltalk/amber/wiki/FAQ#i-am-integrating-a-javascript-library-and-i-need-to-add-its-amdjson-file-what-should-i-use-as-path-there). Please feel free to copy it from there and further process it.

**Comment by sebastianconcept** [comment]
Sure @hhzl thanks.

Are you the author of all the other FAQ questions and answers?

**Comment by hhzl** [comment]
I am the author of _some_ of them. How many I have lost track of.  I
have been curating that list for some time now. I am fine if you
process them in the trello board and later push them to the FAQ on
docs.amber-lang.net. When that process is finished we can delete the
content of the wiki page and only keep a link to the faq on
docs.amber-lang.net.

**Comment by sebastianconcept** [comment]
sounds good @hhzl 

I'e added some as trello cards here in the column `Doing` and `Ready to review`:
https://trello.com/c/G4KpC2en/54-i-am-integrating-a-javascript-library-and-i-need-to-add-it-s-amd-json-file-what-should-i-use-as-path-there

The idea is to add more but I have no time for that today, I have a demo to deliver.

It would be great if you can add some

If you do please announce here so the team can process:
https://gitter.im/amber-smalltalk/amber-documentation
